services:
  - type: web
    name: notes-express-backend
    env: python
    region: singapore # or ohio, frankfurt, oregon depending on your users
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    rootDir: "backend" # This tells Render that your Python code is inside the backend/ folder
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0 # Use your local python version
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
